### ISSUE TITLE
Some extractions are missing provenance context

### ISSUE THREAD

**Issue by ThomasSchellenbergNextCentury** [usc-isi-i2/dig3-extractions#14]
Some extractions are missing their provenance context.  This appears to be extractor-specific:  `city`, `phone`, `price`, and `review_id` all have missing provenance information.
Here is an example:
https://dig3.memexproxy.com/elasticsearch/dig-etk-search/ads/B5FDC1EEA8EBCA711E59A866DBF6E84EB8E9677BF7223E371985D1122DCAC1AB

**Comment by saggu** [comment]
Its not a bug. These extractors are either very customised or do not support context creation.
Moving forward, phone will have context once we phase out current phone extractor and introduce the spacy phone extractor.
