### ISSUE TITLE
Do not automatically assign the current year to date extractions

### ISSUE THREAD

**Issue by ThomasSchellenbergNextCentury** [usc-isi-i2/dig3-extractions#6]
Whenever a date is mentioned without a year (like `july 31`) we automatically give it the current year `2017`.  This causes a lot of confusion with older ads posted in 2013/2014/2015.  Ideally, we'd use a year stated elsewhere in the ad, but we could alternatively just ignore these extractions.  Here are a couple of examples:
https://dig3.memexproxy.com/offer.html?id=72A2740A5DFCBBE7EBADD87C374D70BBF7CE554EE638E76939091B2B4B34A7E1
https://dig3.memexproxy.com/offer.html?id=98FA394558BFE68FFC9C37D5481FD2B9EC7E29A0ACF6184BAF6C88DAD24570AB

**Comment by saggu** [comment]
Fixed. This problem should not occur in the next run
